[2024-07-19T15:07:46.857+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T15:07:46.879+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: newdag.e_valida scheduled__2024-07-19T13:30:00+00:00 [queued]>
[2024-07-19T15:07:46.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: newdag.e_valida scheduled__2024-07-19T13:30:00+00:00 [queued]>
[2024-07-19T15:07:46.889+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-19T15:07:46.901+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): e_valida> on 2024-07-19 13:30:00+00:00
[2024-07-19T15:07:46.908+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1779) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T15:07:46.909+0000] {standard_task_runner.py:64} INFO - Started process 1784 to run task
[2024-07-19T15:07:46.909+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'newdag', 'e_valida', 'scheduled__2024-07-19T13:30:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/newdag.py', '--cfg-path', '/tmp/tmprsgwfqpl']
[2024-07-19T15:07:46.910+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask e_valida
[2024-07-19T15:07:46.945+0000] {task_command.py:426} INFO - Running <TaskInstance: newdag.e_valida scheduled__2024-07-19T13:30:00+00:00 [running]> on host 11dd3049148c
[2024-07-19T15:07:47.012+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='newdag' AIRFLOW_CTX_TASK_ID='e_valida' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-19T13:30:00+00:00'
[2024-07-19T15:07:47.013+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T15:07:47.014+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-07-19T15:07:47.022+0000] {python.py:237} INFO - Done. Returned value was: nvalido
[2024-07-19T15:07:47.023+0000] {branch.py:36} INFO - Branch into nvalido
[2024-07-19T15:07:47.023+0000] {skipmixin.py:178} INFO - Following branch nvalido
[2024-07-19T15:07:47.037+0000] {skipmixin.py:246} INFO - Skipping tasks [('valido', -1)]
[2024-07-19T15:07:47.054+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T15:07:47.067+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=newdag, task_id=e_valida, run_id=scheduled__2024-07-19T13:30:00+00:00, execution_date=20240719T133000, start_date=20240719T150746, end_date=20240719T150747
[2024-07-19T15:07:47.082+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-19T15:07:47.105+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-19T15:07:47.106+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
