[2024-07-19T15:15:31.708+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T15:15:31.738+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: newdag.nvalido scheduled__2024-07-19T13:30:00+00:00 [queued]>
[2024-07-19T15:15:31.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: newdag.nvalido scheduled__2024-07-19T13:30:00+00:00 [queued]>
[2024-07-19T15:15:31.747+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-07-19T15:15:31.759+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): nvalido> on 2024-07-19 13:30:00+00:00
[2024-07-19T15:15:31.765+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1963) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T15:15:31.767+0000] {standard_task_runner.py:64} INFO - Started process 1966 to run task
[2024-07-19T15:15:31.767+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'newdag', 'nvalido', 'scheduled__2024-07-19T13:30:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/newdag.py', '--cfg-path', '/tmp/tmpvtkhzfuc']
[2024-07-19T15:15:31.768+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask nvalido
[2024-07-19T15:15:31.810+0000] {task_command.py:426} INFO - Running <TaskInstance: newdag.nvalido scheduled__2024-07-19T13:30:00+00:00 [running]> on host 11dd3049148c
[2024-07-19T15:15:31.883+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='newdag' AIRFLOW_CTX_TASK_ID='nvalido' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-19T13:30:00+00:00'
[2024-07-19T15:15:31.884+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T15:15:31.885+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-19T15:15:31.885+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Quantidade não OK'"]
[2024-07-19T15:15:31.895+0000] {subprocess.py:86} INFO - Output:
[2024-07-19T15:15:31.896+0000] {subprocess.py:93} INFO - Quantidade não OK
[2024-07-19T15:15:31.897+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-19T15:15:31.897+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T15:15:31.916+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=newdag, task_id=nvalido, run_id=scheduled__2024-07-19T13:30:00+00:00, execution_date=20240719T133000, start_date=20240719T151531, end_date=20240719T151531
[2024-07-19T15:15:31.941+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-19T15:15:31.953+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T15:15:31.955+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
