[2024-07-19T15:11:20.446+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T15:11:20.467+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: newdag.nvalido scheduled__2024-07-19T13:30:00+00:00 [queued]>
[2024-07-19T15:11:20.474+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: newdag.nvalido scheduled__2024-07-19T13:30:00+00:00 [queued]>
[2024-07-19T15:11:20.475+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-07-19T15:11:20.485+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): nvalido> on 2024-07-19 13:30:00+00:00
[2024-07-19T15:11:20.490+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1874) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T15:11:20.491+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'newdag', 'nvalido', 'scheduled__2024-07-19T13:30:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/newdag.py', '--cfg-path', '/tmp/tmpwt6bna3h']
[2024-07-19T15:11:20.492+0000] {standard_task_runner.py:64} INFO - Started process 1878 to run task
[2024-07-19T15:11:20.492+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask nvalido
[2024-07-19T15:11:20.523+0000] {task_command.py:426} INFO - Running <TaskInstance: newdag.nvalido scheduled__2024-07-19T13:30:00+00:00 [running]> on host 11dd3049148c
[2024-07-19T15:11:20.577+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='newdag' AIRFLOW_CTX_TASK_ID='nvalido' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-19T13:30:00+00:00'
[2024-07-19T15:11:20.578+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T15:11:20.578+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-19T15:11:20.579+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Quantidade não OK'"]
[2024-07-19T15:11:20.588+0000] {subprocess.py:86} INFO - Output:
[2024-07-19T15:11:20.589+0000] {subprocess.py:93} INFO - Quantidade não OK
[2024-07-19T15:11:20.589+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-19T15:11:20.590+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T15:11:20.606+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=newdag, task_id=nvalido, run_id=scheduled__2024-07-19T13:30:00+00:00, execution_date=20240719T133000, start_date=20240719T151120, end_date=20240719T151120
[2024-07-19T15:11:20.625+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-19T15:11:20.637+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T15:11:20.638+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
