[2024-07-23T14:45:56.659+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-23T14:45:56.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: newdag.nvalido scheduled__2024-07-19T18:30:00+00:00 [queued]>
[2024-07-23T14:45:56.686+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: newdag.nvalido scheduled__2024-07-19T18:30:00+00:00 [queued]>
[2024-07-23T14:45:56.687+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-23T14:45:56.696+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): nvalido> on 2024-07-19 18:30:00+00:00
[2024-07-23T14:45:56.701+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-23T14:45:56.703+0000] {standard_task_runner.py:64} INFO - Started process 83 to run task
[2024-07-23T14:45:56.703+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'newdag', 'nvalido', 'scheduled__2024-07-19T18:30:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/firstdag.py', '--cfg-path', '/tmp/tmplzr8yi3k']
[2024-07-23T14:45:56.703+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask nvalido
[2024-07-23T14:45:56.737+0000] {task_command.py:426} INFO - Running <TaskInstance: newdag.nvalido scheduled__2024-07-19T18:30:00+00:00 [running]> on host 11dd3049148c
[2024-07-23T14:45:56.813+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='newdag' AIRFLOW_CTX_TASK_ID='nvalido' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T18:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-19T18:30:00+00:00'
[2024-07-23T14:45:56.815+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-23T14:45:56.816+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-23T14:45:56.816+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Quantidade não OK'"]
[2024-07-23T14:45:56.826+0000] {subprocess.py:86} INFO - Output:
[2024-07-23T14:45:56.827+0000] {subprocess.py:93} INFO - Quantidade não OK
[2024-07-23T14:45:56.827+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-23T14:45:56.828+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-23T14:45:56.845+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=newdag, task_id=nvalido, run_id=scheduled__2024-07-19T18:30:00+00:00, execution_date=20240719T183000, start_date=20240723T144556, end_date=20240723T144556
[2024-07-23T14:45:56.876+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-23T14:45:56.887+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-23T14:45:56.889+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
